=== AndreeRoudon/alpacha-api/src/main/resources/ProductSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.org/ProductSchema"
           xmlns:tns="http://www.example.org/ProductSchema"
           elementFormDefault="qualified">

    <xs:complexType name="Product">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="image" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ProductData">
        <xs:sequence>
            <xs:element name="product1" type="tns:Product"/>
            <xs:element name="product2" type="tns:Product"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="ProductDataSet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ProductData" type="tns:ProductData" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AndreeRoudon/alpacha-api/src/main/resources/DonneesDeTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ProductDataSet xmlns:tns="http://www.example.org/ProductSchema"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.example.org/ProductSchema ProductSchema.xsd">
    <tns:ProductData>
        <tns:product1>
            <tns:id>1</tns:id>
            <tns:name>pull violet</tns:name>
            <tns:price>29.99</tns:price>
            <tns:image>image</tns:image>
        </tns:product1>
        <tns:product2>
            <tns:id>2</tns:id>
            <tns:name>pull rouge</tns:name>
            <tns:price>39.99</tns:price>
            <tns:image>image2</tns:image>
        </tns:product2>
    </tns:ProductData>
    <tns:ProductData>
        <tns:product1>
            <tns:id>3</tns:id>
            <tns:name>pull bleu</tns:name>
            <tns:price>49.99</tns:price>
            <tns:image>image3</tns:image>
        </tns:product1>
        <tns:product2>
            <tns:id>4</tns:id>
            <tns:name>pull vert</tns:name>
            <tns:price>59.99</tns:price>
            <tns:image>image4</tns:image>
        </tns:product2>
    </tns:ProductData>
</tns:ProductDataSet>
